### PR TITLE
Pr/eslint

### PR DESCRIPTION
**Pull request by icaroponce**
Hi, 

As discussed in #11, I implemented an es6 style guide, the [Airbnb](https://github.com/airbnb/javascript) one, to ensure a stricter code style guide to this project.

I also could cut off a couple lines of code in some methods, I believe they are clearer now, although I'm not completely satisfied with some points of code which I've implemented and intend to keep working on them later. 

There're some unsolved eslint errors left, all regarding to the class structure and OOP. 
I opened an issue: #12 to discuss this design. 

You can run eslint like this: `./node_modules/.bin/eslint .`, or even install it globally, which is not very recommended. 

Hope you'll like it. 
Thanks.

### CODE REVIEW

**Comment by icaroponce** [comment]
@waseem18 can you please review it?

**Comment by waseem18** [comment]
Sorry for the delay @icaroponce . I'll review it over the weekend and merge it :+1:

**Comment by icaroponce** [comment]
Hi @waseem18 

Looking forward to hear back from you after you've reviewed it.

**Comment by icaroponce** [comment]
Hi @waseem18 

Do you have some update on this subject?

**Comment by waseem18** [comment]
So sorry @icaroponce for the delay! I'll review and close it tonight :+1: 

Good progress by the way :1st_place_medal:

**Comment by icaroponce** [comment]
@waseem18 is there any update for this matter? I look forward to see what think about it

Cheers,
Icaro

**Comment by icaroponce** [comment]
Hi @waseem18.
I really would like to hear back from you about it.
Please, let me know some update on this matter as soon as you can.

**Comment by waseem18** [comment]
Merged! Sorry for the delay.

**Pull request merged**
